version: '3.9'

services:

  mysql-tokosyfa:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-tokosyfa
    restart: always
    volumes:
      - mysql-tokosyfa-volume:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - tokosyfa-networks
    environment:
      - MYSQL_DATABASE=tokosyfa
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin-tokosyfa:
    image: phpmyadmin:5.2
    container_name: phpmyadmin-tokosyfa
    restart: always
    ports:
      - 8890:80
    networks:
      - tokosyfa-networks
    depends_on:
      - mysql-tokosyfa
    environment:
      - PMA_USER=root
      - PMA_ARBITRARY=1
      - PMA_PASSWORD=root
      - PMA_PMADB=tokosyfa
      - PMA_HOST=mysql-tokosyfa

networks:
  tokosyfa-networks:

volumes:
  mysql-tokosyfa-volume:
